# -*- coding: utf-8 -*-
"""sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2FFE5u7Rbwg63tVOzaRGihObhbzWDAt
"""

n1= 5
n2 = 10
if n1>n2:
  print(n1)
else:
  print(n2)

if n1<n2:
  print(n1)
else:
  print(n2)